admin:
  existingSecret: grafana
  userKey: admin-user
  passwordKey: admin-password
replicas: 1
service:
  type: ${GRAFANA_SERVICE_TYPE}
persistence:
  enabled: true
  storageClassName: ${GRAFANA_STORAGE_CLASS}
  size: ${GRAFANA_STORAGE}
rbac:
  create: true
resources:
  requests:
    cpu: ${GRAFANA_CPU_REQUEST}
    memory: ${GRAFANA_MEMORY_REQUEST}
  limits:
    cpu: ${GRAFANA_CPU_LIMIT}
    memory: ${GRAFANA_MEMORY_LIMIT}
grafana.ini:
  analytics:
    check_for_updates: true
  log:
    mode: console
