apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: ${SEARCH_UI_NAME}
  namespace: ${SEARCH_NAMESPACE}
spec:
  version: ${ELASTICSEARCH_VERSION}
  count: ${KIBANA_COUNT}
  elasticsearchRef:
    name: ${SEARCH_CLUSTER_NAME}
  http:
    service:
      spec:
        type: ${KIBANA_SERVICE_TYPE}
    tls:
      certificate: {}
  monitoring:
    logs: {}
    metrics: {}
  config:
    monitoring.ui.ccs.enabled: false
    xpack.security.authc.providers:
      basic:
        basic1:
          enabled: true
          order: 0
  podTemplate:
    spec:
      tolerations:
        - key: role
          operator: Equal
          value: data
          effect: NoSchedule
      containers:
        - name: kibana
          resources:
            requests:
              cpu: ${KIBANA_CPU_REQUEST}
              memory: ${KIBANA_MEMORY_REQUEST}
            limits:
              cpu: ${KIBANA_CPU_LIMIT}
              memory: ${KIBANA_MEMORY_LIMIT}
