apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: search-stack
  namespace: observability
spec:
  version: 8.19.8
  auth: {}
  http:
    tls:
      certificate: {}
  transport:
    tls:
      certificate: {}
      certificateAuthorities: {}
  monitoring:
    logs: {}
    metrics: {}
  updateStrategy:
    changeBudget: {}
  nodeSets:
    - name: master
      count: 3
      config:
        node.roles: ["master"]
      podTemplate:
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    topologyKey: topology.kubernetes.io/zone
                    labelSelector:
                      matchLabels:
                        elasticsearch.k8s.elastic.co/cluster-name: search-stack
                        elasticsearch.k8s.elastic.co/statefulset-name: search-stack-es-master
          nodeSelector:
            elasticsearch.role: master
            topology.kubernetes.io/zone: example-region-1a
          tolerations:
            - key: elasticsearch.role
              operator: Equal
              value: master
              effect: NoSchedule
          initContainers:
            - name: sysctl
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
              securityContext:
                privileged: true
                runAsUser: 0
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms2g -Xmx2g
              resources:
                requests:
                  cpu: "1"
                  memory: 4Gi
                limits:
                  cpu: "1"
                  memory: 4Gi
    - name: hot
      count: 3
      config:
        indices.memory.index_buffer_size: 20%
        node.attr.data: hot
        node.roles: ["data_hot", "data_content", "ingest", "transform"]
        thread_pool.write.queue_size: 2000
        thread_pool.write.size: 6
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: premium-rwo
            resources:
              requests:
                storage: 2300Gi
      podTemplate:
        spec:
          nodeSelector:
            elasticsearch.role: data-hot
            topology.kubernetes.io/zone: example-region-1a
          tolerations:
            - key: elasticsearch.role
              operator: Equal
              value: data-hot
              effect: NoSchedule
            - key: elasticsearch.role
              operator: Equal
              value: hot
              effect: NoSchedule
          initContainers:
            - name: sysctl
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
              securityContext:
                privileged: true
                runAsUser: 0
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms14g -Xmx14g
              resources:
                requests:
                  cpu: "6"
                  memory: 26Gi
                limits:
                  cpu: "6"
                  memory: 26Gi
    - name: warm
      count: 3
      config:
        node.attr.data: warm
        node.roles: ["data_warm"]
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: standard
            resources:
              requests:
                storage: 4000Gi
      podTemplate:
        spec:
          nodeSelector:
            elasticsearch.role: data-warm
            topology.kubernetes.io/zone: example-region-1a
          tolerations:
            - key: elasticsearch.role
              operator: Equal
              value: data-warm
              effect: NoSchedule
            - key: elasticsearch.role
              operator: Equal
              value: warm
              effect: NoSchedule
          initContainers:
            - name: sysctl
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
              securityContext:
                privileged: true
                runAsUser: 0
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms6g -Xmx6g
              resources:
                requests:
                  cpu: "2"
                  memory: 12Gi
                limits:
                  cpu: "2"
                  memory: 12Gi
