timestamp: "@timestamp"
client_ip: "ClientIP.keyword"
asn: "ClientASN"
path: "ClientRequestPath.keyword"
uri: "ClientRequestURI.keyword"
user_agent: "ClientRequestUserAgent.keyword"
edge_status: "EdgeResponseStatus"
origin_status: "OriginResponseStatus"
security_action: "SecurityAction.keyword"
security_actions: "SecurityActions.keyword"
security_rule_description: "SecurityRuleDescription.keyword"
device_id: "RequestHeaders.device-uid.keyword"
client_hint: "RequestHeaders.client-id.keyword"
session_id: "RequestHeaders.session-id.keyword"
access_user: "RequestHeaders.ed-access-user.keyword"
account_id: "RequestHeaders.account-id.keyword"
account_created_at: ""
challenge_outcome: ""
