apiVersion: v1
kind: Secret
metadata:
  name: investigation-ops-secret
  namespace: investigations
type: Opaque
stringData:
  WEBHOOK_SHARED_TOKEN: ${INVESTIGATION_WEBHOOK_SHARED_TOKEN}
  ELASTICSEARCH_USERNAME: ${INVESTIGATION_ELASTICSEARCH_USERNAME}
  ELASTICSEARCH_PASSWORD: ${INVESTIGATION_ELASTICSEARCH_PASSWORD}
  SLACK_WEBHOOK_URL: ${INVESTIGATION_SLACK_WEBHOOK_URL}
