apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-ingest-config
  namespace: observability
data:
  BATCH_SIZE: "20"
  ES_HOST: "https://search-stack-es-http.observability:9200"
  ES_INDEX: "edge-logs"
  ES_USER: "elastic"
